/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonitorsIndexRouteImport } from './routes/monitors.index'
import { Route as IncidentsIndexRouteImport } from './routes/incidents.index'
import { Route as TracesTraceIdRouteImport } from './routes/traces.$traceId'
import { Route as MonitorsMonitorIdRouteImport } from './routes/monitors.$monitorId'
import { Route as IncidentsIncidentIdRouteImport } from './routes/incidents.$incidentId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorsIndexRoute = MonitorsIndexRouteImport.update({
  id: '/monitors/',
  path: '/monitors/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorsMonitorIdRoute = MonitorsMonitorIdRouteImport.update({
  id: '/monitors/$monitorId',
  path: '/monitors/$monitorId',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: '/incidents/$incidentId',
  path: '/incidents/$incidentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/settings': typeof SettingsRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/monitors/$monitorId': typeof MonitorsMonitorIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/monitors/': typeof MonitorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/settings': typeof SettingsRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/monitors/$monitorId': typeof MonitorsMonitorIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/incidents': typeof IncidentsIndexRoute
  '/monitors': typeof MonitorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/settings': typeof SettingsRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/monitors/$monitorId': typeof MonitorsMonitorIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/monitors/': typeof MonitorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/settings'
    | '/incidents/$incidentId'
    | '/monitors/$monitorId'
    | '/traces/$traceId'
    | '/incidents/'
    | '/monitors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/settings'
    | '/incidents/$incidentId'
    | '/monitors/$monitorId'
    | '/traces/$traceId'
    | '/incidents'
    | '/monitors'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/settings'
    | '/incidents/$incidentId'
    | '/monitors/$monitorId'
    | '/traces/$traceId'
    | '/incidents/'
    | '/monitors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  SettingsRoute: typeof SettingsRoute
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
  MonitorsMonitorIdRoute: typeof MonitorsMonitorIdRoute
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  MonitorsIndexRoute: typeof MonitorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitors/': {
      id: '/monitors/'
      path: '/monitors'
      fullPath: '/monitors/'
      preLoaderRoute: typeof MonitorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitors/$monitorId': {
      id: '/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof MonitorsMonitorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$incidentId': {
      id: '/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  SettingsRoute: SettingsRoute,
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
  MonitorsMonitorIdRoute: MonitorsMonitorIdRoute,
  TracesTraceIdRoute: TracesTraceIdRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  MonitorsIndexRoute: MonitorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
